# Generated by Django 5.1.4 on 2025-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('DealerId', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
            ],
        ),
    ]
