# Generated by Django 3.2.25 on 2025-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='DealerId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='event',
            field=models.CharField(default='testvalue', max_length=50),
        ),
        migrations.AddField(
            model_name='dealer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
