# Generated by Django 3.2.25 on 2025-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_auto_20250327_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(default='testvalue', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
